### ISSUE TITLE
Token not returned to callback

### ISSUE THREAD

**Issue by shivamlekhi** [getstation/electron-google-oauth2#1]
Hi, 
Thank you so much for writing this plugin. I'm trying to authenticate and it works perfectly until I sign in and give permission, it takes me to a screen where it wants me to copy and paste the code instead of returning it to the callback in the code.

Perhaps I'm doing something wrong. Can you please assist me?

You are a life saver, thanks!

**Comment by magne4000** [comment]
Wow sorry, didn't saw that issue until today... I hope that you manage to find the source of your issue. If not, feel free to reopen it!
