### ISSUE TITLE
Ability to generateAuthUrl with propmt param

### ISSUE THREAD

**Issue by vovasit91** [getstation/electron-google-oauth2#12]
If you miss to save refresh token in your app or if your refresh token got deleted from your app it would be good to have ability to generate Authorization url with extra option prompt: consent

In code it would look like this
`let url = this.oauth2Client.generateAuthUrl({
            access_type: 'offline',
            scope: this.scopes,
            prompt: 'consent',
            redirect_uri: `http://127.0.0.1:${this.options.loopbackInterfaceRedirectionPort}/callback`
        });` because without this param next authorization will generate all tokens except refresh_token.

**Comment by hijklmno** [comment]
I've made a relevant PR in #23
