### ISSUE TITLE
How do you store and retrieve the key for the client secret?

### ISSUE THREAD

**Issue by vakkiee** [getstation/electron-google-oauth2#51]
Isn't CLIENT_SECRET not actually a secret?
Is it okay not to conceal CLIENT_SECRET?

```
 const myApiOauth = new ElectronGoogleOAuth2(
    'CLIENT_ID',
    'CLIENT_SECRET',
    ['https://www.googleapis.com/auth/drive.metadata.readonly']
  );
```

In case you need to retrieve CLIENT_SECRET on the client side, there might be a security vulnerability regardless of where it's stored...
I might just not be understanding it correctly, but I would greatly appreciate some advice or specific solutions.

**Comment by magne4000** [comment]
`CLIENT_SECRET` should be considered secret, and using it directly inside an Electron app is not the safest/recommended way to do it (an actual hosted web page would be the right way to do it, as you can conceal the secret behind it).
If you consider using it in a software where the token being stolen is not that much of an issue (i.e. if you are NOT using the same ID or SECRET on a backend service for instance) you "should" be ok, but you should consider carefully before comitting to using this package for those security issues.

**Comment by vakkiee** [comment]
@magne4000 
Thank you very much for your kind reply! We will discuss as a team and consider the use of this package.
